---
title: "115presentation"
format: revealjs
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(bayesrules)
library(dplyr)
library(tidyverse)
library(rstanarm)
library(bayesplot)
library(broom.mixed)
library(tidybayes)
vgames_df <- read.csv("./video_games.csv")
```

```{r}
# reading the data in as a dataframe but then reassign data frame with the 
# variables = review_score, console, length, genres, sales where response 
# is review score

vgames_df <- vgames_df %>% 
         rename(review_score = Metrics.Review.Score, console = Release.Console, 
         length = Length.All.PlayStyles.Average, genres = Metadata.Genres, 
         sales = Metrics.Sales, rating=Release.Rating)

vgames_df <- vgames_df %>% 
  select(review_score, console, length, genres, sales, rating)

head(vgames_df)
```

---

```{r}
# Changes genres into a single genre
for (row in 1:nrow(vgames_df)) {
  genres <- strsplit(vgames_df$genres[row], split = ",", fixed = TRUE)[[1]]
  if(length(genres) > 0) { 
    i <- sample(length(genres), 1) 
    vgames_df$genres[row] <- genres[i]
  }
}

head(vgames_df)
```

---

## Model 7: Genres + Console
```{r}
# Model 7: X = genres + console
vgame_model_7 <- stan_glm(
  review_score ~ genres + console,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735, refresh=FALSE)
```

---

```{r}
ggplot(vgames_df, aes(y=review_score, x=console, color=genres)) +
  geom_boxplot()
```

---

```{r}
tidy(vgame_model_7, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```

---

## Model 4: Console
```{r}
# Model 4: X = console
vgame_model_4 <- stan_glm(
  review_score ~ console,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(70, 10),
  prior = normal(0, 2.5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735, refresh = FALSE)
```

---

```{r}
as.data.frame(vgame_model_4) %>%
  mutate(DS = `(Intercept)`,
         Wii = `(Intercept)` + `consoleNintendo Wii`,
         PS3 = `(Intercept)` + `consolePlayStation 3`,
         PSP = `(Intercept)` + `consoleSony PSP`,
         X360 = `(Intercept)` + consoleX360) %>%
  mcmc_areas(pars = c("DS", "Wii", "PS3", "PSP", "X360"))
```

---

```{r}
tidy(vgame_model_4, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```

---

## Model 11: X = All Predictors
```{r}
# Model 11: X = everything
vgame_model_11 <- stan_glm(
  review_score ~ .,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735, refresh=FALSE)
```

---

```{r}
tidy(vgame_model_11, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```








