---
title: "Group Presentation"
format:
  html:
    theme: default
    toc: true
    number-sections: true
---

# Intro

- Video games have been around for decades since the days of the regular 
 Nintendo where it was first released in the 80s. 
 
- The market of video games has become a multi-billion dollar industry

- Video games have risen in cost which has made buying a video game to become
  a much more weighted decision for the average consumer

- Review scores influence customer buying options, and so developer interests
  about what games to make is an important market decision
  
- Esports is becoming a much more popular activity across mainstream entertainment

# Research Goals

- We are hoping for this project endeavor to achieve two main objectives:

  - Provide strong inference from our chosen features about how well video game
    is expected to be scored. 
  - Provide key insights for key stakeholders 

# Priors

In our pursuit for coming up with informative priors for our analysis, We 
leveraged 3 different data sets and news reports/articles to formulate our 
expectations.

  - the three data sets came from sources Metacritic, Steam, IGN. 
  - Some of these datasets consisted of journalist review scores or/and 
    userscores
    
# Priors: Intercept

Of the most assured priors, we used metacritic and steam to formulate our 
priors for reviews scores and platforms. 

What we found:

- [average metascore](./img/ave_metascore.png)

- [average userscore on metacritic](./img/ave_meta_userscore.png)

- [average userscore on steam](./img/ave_steam_userscore.png)

- prior model: \(N(69.25, 16.618^2)\)

# Platforms

We used the Metacritic data set to formulate our prior by looking at both the 
metascore and userscore:

- [average metascore by platform](./img/metascore_platform.png)
- [average userscore by platform](./img/ave_meta_userscore_platform.png)

- Prior model: \(N(68.485, 3.5825^2)\)

# Genres 

We used the IGN dataset to inform us of a generalized prior:

- [ign genre distribution](./img/ave_ign_genres_score.png)

- Prior model: \(N(65.81,11.33^2)\)

# Sales 

- As an outlet for our prior, we leveraged several online articles. Of note, we 
  found that the average sales of a video game were 277,500. 

- Without an explicit variance, we used a a heuristic to approximate a variance
  of 197,500
  
- Thus, our chosen prior model: \(N(277,500,197,500^2)\)

# Rating & Game Length

Upon review of literature from external sources, we have chosen to go with vague
priors for both of these features. This is due to information informing us 
that there may be no connection between average review scores and their rating or 
game length. Thus:

- vague prior: \(N(0, 5)\)