---
title: "project115"
author: "Alfonso Vieyra"
date: "3/18/2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bayesrules)
library(dplyr)
library(tidyverse)
library(rstanarm)
library(bayesplot)
library(broom.mixed)
library(tidybayes)
vgames_df <- read.csv("./video_games.csv")
```

### Clean data 

```{r}
# reading the data in as a dataframe but then reassign data frame with the 
# variables = review_score, console, length, genres, sales where response 
# is review score

vgames_df <- vgames_df %>% 
         rename(review_score = Metrics.Review.Score, console = Release.Console, 
         length = Length.All.PlayStyles.Average, genres = Metadata.Genres, 
         sales = Metrics.Sales, rating=Release.Rating)

vgames_df <- vgames_df %>% 
  select(review_score, console, length, genres, sales, rating)

head(vgames_df)
```

```{r}
# Changes genres into a single genre
for (row in 1:nrow(vgames_df)) {
  genres <- strsplit(vgames_df$genres[row], split = ",", fixed = TRUE)[[1]]
  if(length(genres) > 0) { 
    i <- sample(length(genres), 1) 
    vgames_df$genres[row] <- genres[i]
  }
}

head(vgames_df)
```


```{r}
colSums(is.na(vgames_df))
```

```{r}
ggplot(vgames_df, aes(x = length, y = review_score)) + 
  geom_point(size = 0.5) + xlim(0,100) + ggtitle(" Game Review Score vs. Game Length")
```

```{r}
ggplot(vgames_df, aes(x = sales, y = review_score)) + 
  geom_point(size = 0.5) + ggtitle(" Game Review Score vs. Game Sales")
```

```{r}
ggplot(vgames_df, aes(x=review_score)) + geom_histogram() + ggtitle("Review Score Histogram")
```

```{r}
ggplot(vgames_df, aes(x=review_score)) + geom_histogram() + facet_wrap(genres ~ ., scales = "free") + ggtitle("Histograms for Genres")
```

```{r}
ggplot(vgames_df, aes(x=review_score)) + geom_histogram() + facet_wrap(console ~ ., scales = "free") + ggtitle("Histograms for Consoles")
```

```{r}
ggplot(vgames_df, aes(x=review_score)) + geom_histogram() + facet_wrap(rating ~ ., scales = "free") + ggtitle("Histograms for Ratings")
```


```{r}
# Using a Normal Regression
# Priors:
#   Normal(69.25, 16.618) for Beta_0c
#   Vague priors for the other betas
#   Vague prior for sigma
# Model 1: X = genres

vgame_model_1 <- stan_glm(
  review_score ~ genres,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_1)
mcmc_dens_overlay(vgame_model_1)
mcmc_acf(vgame_model_1)
```

```{r}
tidy(vgame_model_1, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```

```{r}
as.data.frame(vgame_model_1) %>%
  mutate(Action = `(Intercept)`,
         Adventure = `(Intercept)` + genresAdventure,
         Educational = `(Intercept)` + genresEducational,
         Racing = `(Intercept)` + `genresRacing / Driving`,
         RPG = `(Intercept)` + `genresRole-Playing (RPG)`,
         Simulation = `(Intercept)` + genresSimulation,
         Sports = `(Intercept)` + genresSports,
         Strategy = `(Intercept)` + genresStrategy) %>%
  mcmc_areas(pars = c("Action", "Adventure", "Educational", "Racing", "RPG",
                      "Simulation", "Sports", "Strategy"))
```


```{r}
# Model 2: X = sales
vgame_model_2 <- stan_glm(
  review_score ~ sales,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_2)
mcmc_dens_overlay(vgame_model_2)
mcmc_acf(vgame_model_2)
```

```{r}
tidy(vgame_model_2, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```

```{r}
vgames_df %>%
  add_fitted_draws(vgame_model_2, n = 100) %>%
  ggplot(aes(x=sales, y=review_score)) +
  geom_point(size=0.5) +
  geom_line(aes(y=.value, group=.draw))
```


```{r}
# Model 3: X = length
vgame_model_3 <- stan_glm(
  review_score ~ length,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_3)
mcmc_dens_overlay(vgame_model_3)
mcmc_acf(vgame_model_3)
```

```{r}
tidy(vgame_model_3, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```

```{r}
vgames_df %>%
  add_fitted_draws(vgame_model_3, n = 100) %>%
  ggplot(aes(x=length, y=review_score)) +
  geom_point(size=0.5) +
  geom_line(aes(y=.value, group=.draw)) + 
  xlim(0,100)
```


```{r}
# Model 4: X = console

vgame_model_4 <- stan_glm(
  review_score ~ console,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_4)
mcmc_dens_overlay(vgame_model_4)
mcmc_acf(vgame_model_4)
```

```{r}
tidy(vgame_model_4, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```

```{r}
as.data.frame(vgame_model_4) %>%
  mutate(DS = `(Intercept)`,
         Wii = `(Intercept)` + `consoleNintendo Wii`,
         PS3 = `(Intercept)` + `consolePlayStation 3`,
         PSP = `(Intercept)` + `consoleSony PSP`,
         X360 = `(Intercept)` + consoleX360) %>%
  mcmc_areas(pars = c("DS", "Wii", "PS3", "PSP", "X360"))
```

```{r}
# Model 5: X = rating

vgame_model_5 <- stan_glm(
  review_score ~ rating,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_5)
mcmc_dens_overlay(vgame_model_5)
mcmc_acf(vgame_model_5)
```

```{r}
tidy(vgame_model_5, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```

```{r}
as.data.frame(vgame_model_5) %>%
  mutate(ratingE = `(Intercept)`,
         ratingM = `(Intercept)` + ratingM,
         ratingT = `(Intercept)` + ratingT) %>%
  mcmc_areas(pars = c("ratingE", "ratingM", "ratingT"))
```

```{r}
# Model 6: X = sales + length
vgame_model_6 <- stan_glm(
  review_score ~ sales + length,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_6)
mcmc_dens_overlay(vgame_model_6)
mcmc_acf(vgame_model_6)
```

```{r}
tidy(vgame_model_6, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```


```{r}
# Model 7: X = genres + console
vgame_model_7 <- stan_glm(
  review_score ~ genres + console,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_7)
mcmc_dens_overlay(vgame_model_7)
mcmc_acf(vgame_model_7)
```

```{r}
tidy(vgame_model_7, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```


```{r}
# Model 8: X = genres + console + genres:console
vgame_model_8 <- stan_glm(
  review_score ~ genres + console + genres:console,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_8)
mcmc_dens_overlay(vgame_model_8)
mcmc_acf(vgame_model_8)
```

```{r}
tidy(vgame_model_8, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```

```{r}
ggplot(vgames_df, aes(y=review_score, x=console, color=genres)) +
  geom_boxplot()
```


```{r}
# Model 9: X = genres + sales
vgame_model_9 <- stan_glm(
  review_score ~ genres + sales,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_9)
mcmc_dens_overlay(vgame_model_9)
mcmc_acf(vgame_model_9)
```

```{r}
tidy(vgame_model_9, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```


```{r}
# Model 10: X = genres + sales + genres:sales
vgame_model_10 <- stan_glm(
  review_score ~ genres + sales + genres:sales,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_10)
mcmc_dens_overlay(vgame_model_10)
mcmc_acf(vgame_model_10)
```

```{r}
tidy(vgame_model_10, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```


```{r}
ggplot(vgames_df, aes(y=review_score, x=sales, color=genres)) +
  geom_point(size=0.5) +
  geom_smooth(method="lm", se=FALSE)
```


```{r}
# Model 11: X = everything
vgame_model_11 <- stan_glm(
  review_score ~ .,
  data = vgames_df, family = gaussian,
  prior_intercept = normal(69.25, 16.618),
  prior = normal(0, 5, autoscale = TRUE),
  prior_aux = exponential(1, autoscale = TRUE),
  chains=4, iter=5000*2, seed=84735)
```

```{r}
mcmc_trace(vgame_model_11)
mcmc_dens_overlay(vgame_model_11)
mcmc_acf(vgame_model_11)
```

```{r}
tidy(vgame_model_11, effects = c("fixed", "aux"),
     conf.int = TRUE, conf.level = 0.95)
```


```{r}
new_game_1 <- data.frame(
  genres = factor("Adventure", levels = c("Action", "Adventure", "Strategy", "Sports")),
  console = factor("Nintendo DS", levels = c("Nintendo DS", "Sony PSP", "PlayStation 3")))
posterior_predictive <- posterior_predict(vgame_model_7, newdata = new_game_1)
predictions <- predict(vgame_model_7, newdata = new_game_1, type = "response")
predicted_score <- mean(posterior_predictive)
simulated_reviewscore <- as.data.frame(posterior_predictive)
ggplot(simulated_reviewscore, aes(x = simulated_reviewscore[[1]])) + 
  geom_density(fill = "blue") +
  labs(x = "Predicted Review Score", title = "Predicted Review Scores for Adventure Game in Nintendo DS")
```


```{r}
new_game_2 <- data.frame(
  genres = factor("Action", levels = c("Action", "Adventure", "Strategy", "Sports")),
  sales = 1 
)

posterior_predictive_2 <- posterior_predict(vgame_model_9, newdata = new_game_2)
predictions_2 <- predict(vgame_model_9, newdata = new_game_2, type = "response")
predicted_score_2 <- mean(posterior_predictive_2)
simulated_reviewscore_2 <- as.data.frame(posterior_predictive_2)
ggplot(simulated_reviewscore_2, aes(x = simulated_reviewscore_2[[1]])) +  
  geom_density(fill = "blue") +
  labs(x = "Predicted Review Score", title = "Predicted Review Scores for Action Game with Sales = 1")
```

```{r}
new_game_3 <- data.frame(
  genres = factor("Sports", levels = c("Action", "Adventure", "Strategy", "Sports")),
  sales = 1,
  console = factor("Sony PSP", levels = c("Nintendo DS", "Sony PSP", "PlayStation 3")),
  length = 10,
  rating = factor("E", levels = c("E", "T", "M"))
)

posterior_predictive_3 <- posterior_predict(vgame_model_11, newdata = new_game_3)
predictions_3 <- predict(vgame_model_11, newdata = new_game_3, type = "response")
predicted_score_3 <- mean(posterior_predictive_3)
simulated_reviewscore_3 <- as.data.frame(posterior_predictive_3)
ggplot(simulated_reviewscore_3, aes(x = simulated_reviewscore_3[[1]])) +  
  geom_density(fill = "blue") +
  labs(x = "Predicted Review Score", title = "Predicted Review Scores for Sports Game with Sales = 1, Rating E, and length 10 minutes using Sony PSP")
```

